import { MigrationInterface, QueryRunner } from "typeorm";

export class InitDb1770918072458 implements MigrationInterface {
    name = 'InitDb1770918072458'

    public async up(queryRunner: QueryRunner): Promise<void> {
        await queryRunner.query(`CREATE TABLE \`tokens\` (\`id\` varchar(36) NOT NULL, \`token\` varchar(255) NOT NULL, \`created_at\` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP, \`expired_at\` datetime NOT NULL, \`type\` enum ('verify-account', 'reset-password') NOT NULL, \`used_at\` datetime NULL, \`is_revoked\` tinyint NOT NULL DEFAULT 0, \`user_id\` varchar(255) NOT NULL, PRIMARY KEY (\`id\`)) ENGINE=InnoDB`);
        await queryRunner.query(`CREATE TABLE \`course_teachers\` (\`id\` varchar(36) NOT NULL, \`teacher_id\` varchar(255) NOT NULL, \`course_id\` varchar(255) NOT NULL, \`joined_at\` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP, \`is_owner\` tinyint NOT NULL, UNIQUE INDEX \`UQ_course_teachers_teacher_id_course_id\` (\`teacher_id\`, \`course_id\`), PRIMARY KEY (\`id\`)) ENGINE=InnoDB`);
        await queryRunner.query(`CREATE TABLE \`exam_files\` (\`id\` varchar(36) NOT NULL, \`url\` varchar(255) NOT NULL, \`key\` varchar(255) NOT NULL, \`type\` enum ('question-paper', 'answer-key', 'solution-sheet') NOT NULL, \`created_at\` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP, \`updated_at\` datetime NULL, \`exam_id\` varchar(255) NOT NULL, PRIMARY KEY (\`id\`)) ENGINE=InnoDB`);
        await queryRunner.query(`CREATE TABLE \`fill_in_blank_attempt_answers\` (\`id\` varchar(36) NOT NULL, \`position\` int NOT NULL, \`answer\` varchar(255) NOT NULL, \`attempt_answer_id\` varchar(255) NOT NULL, UNIQUE INDEX \`UQ_fill_in_blank_attempt_answers_attempt_answer_id_position\` (\`attempt_answer_id\`, \`position\`), PRIMARY KEY (\`id\`)) ENGINE=InnoDB`);
        await queryRunner.query(`CREATE TABLE \`question_statements\` (\`id\` varchar(36) NOT NULL, \`text\` varchar(255) NOT NULL, \`position\` int NOT NULL, \`question_id\` varchar(255) NOT NULL, PRIMARY KEY (\`id\`)) ENGINE=InnoDB`);
        await queryRunner.query(`CREATE TABLE \`statement_attempt_answers\` (\`id\` varchar(36) NOT NULL, \`is_correct\` tinyint NOT NULL, \`answer\` tinyint NOT NULL, \`attempt_answer_id\` varchar(255) NOT NULL, \`statement_id\` varchar(255) NOT NULL, UNIQUE INDEX \`UQ_statement_attempt_answers_attempt_answer_id_statement_id\` (\`attempt_answer_id\`, \`statement_id\`), PRIMARY KEY (\`id\`)) ENGINE=InnoDB`);
        await queryRunner.query(`CREATE TABLE \`attempt_answers\` (\`id\` varchar(36) NOT NULL, \`is_fully_correct\` tinyint NULL, \`score\` float NULL, \`time_spent_seconds\` int NOT NULL, \`question_id\` varchar(255) NOT NULL, \`attempt_id\` varchar(255) NOT NULL, UNIQUE INDEX \`UQ_attempt_answers_question_id_attempt_id\` (\`question_id\`, \`attempt_id\`), PRIMARY KEY (\`id\`)) ENGINE=InnoDB`);
        await queryRunner.query(`CREATE TABLE \`exam_attempts\` (\`id\` varchar(36) NOT NULL, \`started_at\` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP, \`ended_at\` datetime NULL, \`score\` float NULL, \`status\` enum ('in-progress', 'completed') NOT NULL DEFAULT 'in-progress', \`exam_id\` varchar(255) NOT NULL, \`student_id\` varchar(255) NOT NULL, PRIMARY KEY (\`id\`)) ENGINE=InnoDB`);
        await queryRunner.query(`CREATE TABLE \`exams\` (\`id\` varchar(36) NOT NULL, \`name\` varchar(255) NOT NULL, \`created_at\` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP, \`updated_at\` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP, \`duration_seconds\` int NULL, \`type\` enum ('practice', 'competition') NOT NULL, \`view_answer_policy\` enum ('never', 'attempt-completed', 'exam-ended') NOT NULL, \`max_attempts\` int NULL, \`start_at\` datetime NULL, \`end_at\` datetime NULL, \`status\` enum ('draft', 'published') NOT NULL, \`created_by\` varchar(255) NOT NULL, \`course_id\` varchar(255) NOT NULL, PRIMARY KEY (\`id\`)) ENGINE=InnoDB`);
        await queryRunner.query(`CREATE TABLE \`stimulus_images\` (\`id\` varchar(36) NOT NULL, \`url\` varchar(255) NOT NULL, \`key\` varchar(255) NOT NULL, \`position\` int NOT NULL, \`stimulus_id\` varchar(255) NOT NULL, PRIMARY KEY (\`id\`)) ENGINE=InnoDB`);
        await queryRunner.query(`CREATE TABLE \`stimulus\` (\`id\` varchar(36) NOT NULL, \`text\` text NOT NULL, \`created_at\` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP, \`updated_at\` datetime NULL, PRIMARY KEY (\`id\`)) ENGINE=InnoDB`);
        await queryRunner.query(`CREATE TABLE \`question_images\` (\`id\` varchar(36) NOT NULL, \`url\` varchar(255) NOT NULL, \`key\` varchar(255) NOT NULL, \`position\` int NOT NULL, \`question_id\` varchar(255) NOT NULL, PRIMARY KEY (\`id\`)) ENGINE=InnoDB`);
        await queryRunner.query(`CREATE TABLE \`question_choices\` (\`id\` varchar(36) NOT NULL, \`text\` varchar(255) NOT NULL, \`position\` int NOT NULL, \`question_id\` varchar(255) NOT NULL, PRIMARY KEY (\`id\`)) ENGINE=InnoDB`);
        await queryRunner.query(`CREATE TABLE \`mcq_correct_answers\` (\`id\` varchar(36) NOT NULL, \`question_id\` varchar(255) NOT NULL, \`correct_answer\` varchar(255) NOT NULL, UNIQUE INDEX \`IDX_3b28b78de8f028aad9b1318cef\` (\`question_id\`), UNIQUE INDEX \`REL_3b28b78de8f028aad9b1318cef\` (\`question_id\`), PRIMARY KEY (\`id\`)) ENGINE=InnoDB`);
        await queryRunner.query(`CREATE TABLE \`fill_in_blank_correct_answers\` (\`id\` varchar(36) NOT NULL, \`question_id\` varchar(255) NOT NULL, \`position\` int NOT NULL, \`correct_answer\` varchar(255) NOT NULL, PRIMARY KEY (\`id\`)) ENGINE=InnoDB`);
        await queryRunner.query(`CREATE TABLE \`statement_correct_answers\` (\`id\` varchar(36) NOT NULL, \`question_id\` varchar(255) NOT NULL, \`statement_id\` varchar(255) NOT NULL, \`correct_answer\` tinyint NOT NULL, UNIQUE INDEX \`IDX_5d2c47d06fd4fba19652a99396\` (\`statement_id\`), UNIQUE INDEX \`UQ_statement_correct_answers_question_id_statement_id\` (\`question_id\`, \`statement_id\`), UNIQUE INDEX \`REL_5d2c47d06fd4fba19652a99396\` (\`statement_id\`), PRIMARY KEY (\`id\`)) ENGINE=InnoDB`);
        await queryRunner.query(`CREATE TABLE \`solution_images\` (\`id\` varchar(36) NOT NULL, \`url\` varchar(255) NOT NULL, \`key\` varchar(255) NOT NULL, \`position\` int NOT NULL, \`solution_id\` varchar(255) NOT NULL, PRIMARY KEY (\`id\`)) ENGINE=InnoDB`);
        await queryRunner.query(`CREATE TABLE \`question_solutions\` (\`id\` varchar(36) NOT NULL, \`text\` text NOT NULL, \`position\` int NOT NULL, \`created_at\` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP, \`updated_at\` datetime NULL, \`question_id\` varchar(255) NOT NULL, PRIMARY KEY (\`id\`)) ENGINE=InnoDB`);
        await queryRunner.query(`CREATE TABLE \`questions\` (\`id\` varchar(36) NOT NULL, \`text\` text NOT NULL, \`type\` enum ('mcq', 'statement', 'fill-blank') NOT NULL, \`position\` int NOT NULL, \`point\` float NOT NULL, \`cognitive_level\` enum ('remember', 'understand', 'apply', 'analyze') NULL, \`exam_id\` varchar(255) NOT NULL, \`topic_id\` varchar(255) NULL, \`stimulus_id\` varchar(255) NULL, PRIMARY KEY (\`id\`)) ENGINE=InnoDB`);
        await queryRunner.query(`CREATE TABLE \`topics\` (\`id\` varchar(36) NOT NULL, \`name\` varchar(255) NOT NULL, \`created_at\` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP, \`course_id\` varchar(255) NOT NULL, PRIMARY KEY (\`id\`)) ENGINE=InnoDB`);
        await queryRunner.query(`CREATE TABLE \`enrollments\` (\`id\` varchar(36) NOT NULL, \`enrolled_at\` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP, \`enrollment_method\` enum ('invitation', 'manual') NOT NULL, \`course_id\` varchar(255) NOT NULL, \`student_id\` varchar(255) NOT NULL, UNIQUE INDEX \`UQ_enrollments_student_id_course_id\` (\`student_id\`, \`course_id\`), PRIMARY KEY (\`id\`)) ENGINE=InnoDB`);
        await queryRunner.query(`CREATE TABLE \`courses\` (\`id\` varchar(36) NOT NULL, \`name\` varchar(255) NOT NULL, \`type\` enum ('public', 'private') NOT NULL, \`created_at\` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP, \`updated_at\` datetime NULL, \`subject_id\` varchar(255) NOT NULL, PRIMARY KEY (\`id\`)) ENGINE=InnoDB`);
        await queryRunner.query(`CREATE TABLE \`subjects\` (\`id\` varchar(36) NOT NULL, \`name\` varchar(255) NOT NULL, \`created_at\` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP, \`updated_at\` datetime NULL, \`created_by\` varchar(255) NOT NULL, PRIMARY KEY (\`id\`)) ENGINE=InnoDB`);
        await queryRunner.query(`CREATE TABLE \`users\` (\`id\` varchar(36) NOT NULL, \`email\` varchar(255) NOT NULL, \`password\` varchar(255) NOT NULL, \`role\` enum ('student', 'teacher', 'admin') NOT NULL, \`created_at\` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP, \`is_verified\` tinyint NULL, \`verified_at\` datetime NULL, PRIMARY KEY (\`id\`)) ENGINE=InnoDB`);
        await queryRunner.query(`CREATE TABLE \`profiles\` (\`id\` varchar(36) NOT NULL, \`first_name\` varchar(255) NOT NULL, \`last_name\` varchar(255) NOT NULL, \`created_at\` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP, \`updated_at\` datetime NULL, \`user_id\` varchar(255) NOT NULL, UNIQUE INDEX \`REL_9e432b7df0d182f8d292902d1a\` (\`user_id\`), PRIMARY KEY (\`id\`)) ENGINE=InnoDB`);
        await queryRunner.query(`CREATE TABLE \`mcq_attempt_answer\` (\`id\` varchar(36) NOT NULL, \`answer\` varchar(255) NOT NULL, \`attempt_answer_id\` varchar(255) NOT NULL, UNIQUE INDEX \`REL_29e96a6705c871fd0022e5d2fd\` (\`attempt_answer_id\`), PRIMARY KEY (\`id\`)) ENGINE=InnoDB`);
        await queryRunner.query(`ALTER TABLE \`tokens\` ADD CONSTRAINT \`FK_Tokens_Users\` FOREIGN KEY (\`user_id\`) REFERENCES \`users\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`course_teachers\` ADD CONSTRAINT \`FK_CourseTeachers_Users\` FOREIGN KEY (\`teacher_id\`) REFERENCES \`users\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`course_teachers\` ADD CONSTRAINT \`FK_CourseTeachers_Courses\` FOREIGN KEY (\`course_id\`) REFERENCES \`courses\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`exam_files\` ADD CONSTRAINT \`FK_ExamFiles_Exams\` FOREIGN KEY (\`exam_id\`) REFERENCES \`exams\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`fill_in_blank_attempt_answers\` ADD CONSTRAINT \`FK_FibAttemptAnswers_AttemptAnswers\` FOREIGN KEY (\`attempt_answer_id\`) REFERENCES \`attempt_answers\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`question_statements\` ADD CONSTRAINT \`FK_QuestionStatements_Questions\` FOREIGN KEY (\`question_id\`) REFERENCES \`questions\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`statement_attempt_answers\` ADD CONSTRAINT \`FK_StatementAttemptAnswers_AttemptAnswers\` FOREIGN KEY (\`attempt_answer_id\`) REFERENCES \`attempt_answers\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`statement_attempt_answers\` ADD CONSTRAINT \`FK_StatementAttemptAnswers_QuestionStatements\` FOREIGN KEY (\`statement_id\`) REFERENCES \`question_statements\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`attempt_answers\` ADD CONSTRAINT \`FK_AttemptAnswers_Questions\` FOREIGN KEY (\`question_id\`) REFERENCES \`questions\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`attempt_answers\` ADD CONSTRAINT \`FK_AttemptAnswers_Attempts\` FOREIGN KEY (\`attempt_id\`) REFERENCES \`exam_attempts\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`exam_attempts\` ADD CONSTRAINT \`FK_Attempts_Exams\` FOREIGN KEY (\`exam_id\`) REFERENCES \`exams\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`exam_attempts\` ADD CONSTRAINT \`FK_Attempts_Users\` FOREIGN KEY (\`student_id\`) REFERENCES \`users\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`exams\` ADD CONSTRAINT \`FK_Exams_Users\` FOREIGN KEY (\`created_by\`) REFERENCES \`users\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`exams\` ADD CONSTRAINT \`FK_Exams_Courses\` FOREIGN KEY (\`course_id\`) REFERENCES \`courses\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`stimulus_images\` ADD CONSTRAINT \`FK_StimulusImages_Stimulus\` FOREIGN KEY (\`stimulus_id\`) REFERENCES \`stimulus\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`question_images\` ADD CONSTRAINT \`FK_QuestionImages_Questions\` FOREIGN KEY (\`question_id\`) REFERENCES \`questions\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`question_choices\` ADD CONSTRAINT \`FK_QuestionChoices_Questions\` FOREIGN KEY (\`question_id\`) REFERENCES \`questions\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`mcq_correct_answers\` ADD CONSTRAINT \`FK_McqCorrectAnswers_Questions\` FOREIGN KEY (\`question_id\`) REFERENCES \`questions\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`fill_in_blank_correct_answers\` ADD CONSTRAINT \`FK_FillInBlankCorrectAnswers_Questions\` FOREIGN KEY (\`question_id\`) REFERENCES \`questions\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`statement_correct_answers\` ADD CONSTRAINT \`FK_StatementCorrectAnswers_Questions\` FOREIGN KEY (\`question_id\`) REFERENCES \`questions\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`statement_correct_answers\` ADD CONSTRAINT \`FK_StatementCorrectAnswers_Statements\` FOREIGN KEY (\`statement_id\`) REFERENCES \`question_statements\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`solution_images\` ADD CONSTRAINT \`FK_SolutionImages_QuestionSolution\` FOREIGN KEY (\`solution_id\`) REFERENCES \`question_solutions\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`question_solutions\` ADD CONSTRAINT \`FK_QuestionSolutions_Questions\` FOREIGN KEY (\`question_id\`) REFERENCES \`questions\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`questions\` ADD CONSTRAINT \`FK_Questions_Exams\` FOREIGN KEY (\`exam_id\`) REFERENCES \`exams\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`questions\` ADD CONSTRAINT \`FK_Questions_Topics\` FOREIGN KEY (\`topic_id\`) REFERENCES \`topics\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`questions\` ADD CONSTRAINT \`FK_Questions_Stimulus\` FOREIGN KEY (\`stimulus_id\`) REFERENCES \`stimulus\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`topics\` ADD CONSTRAINT \`FK_Topics_Courses\` FOREIGN KEY (\`course_id\`) REFERENCES \`courses\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`enrollments\` ADD CONSTRAINT \`FK_Enrollments_Courses\` FOREIGN KEY (\`course_id\`) REFERENCES \`courses\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`enrollments\` ADD CONSTRAINT \`FK_Enrollments_Users\` FOREIGN KEY (\`student_id\`) REFERENCES \`users\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`courses\` ADD CONSTRAINT \`FK_Courses_Subjects\` FOREIGN KEY (\`subject_id\`) REFERENCES \`subjects\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`subjects\` ADD CONSTRAINT \`FK_Subjects_Users\` FOREIGN KEY (\`created_by\`) REFERENCES \`users\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`profiles\` ADD CONSTRAINT \`FK_Profiles_Users\` FOREIGN KEY (\`user_id\`) REFERENCES \`users\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`mcq_attempt_answer\` ADD CONSTRAINT \`FK_McqAttemptAnswers_AttemptAnswers\` FOREIGN KEY (\`attempt_answer_id\`) REFERENCES \`attempt_answers\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
    }

    public async down(queryRunner: QueryRunner): Promise<void> {
        await queryRunner.query(`ALTER TABLE \`mcq_attempt_answer\` DROP FOREIGN KEY \`FK_McqAttemptAnswers_AttemptAnswers\``);
        await queryRunner.query(`ALTER TABLE \`profiles\` DROP FOREIGN KEY \`FK_Profiles_Users\``);
        await queryRunner.query(`ALTER TABLE \`subjects\` DROP FOREIGN KEY \`FK_Subjects_Users\``);
        await queryRunner.query(`ALTER TABLE \`courses\` DROP FOREIGN KEY \`FK_Courses_Subjects\``);
        await queryRunner.query(`ALTER TABLE \`enrollments\` DROP FOREIGN KEY \`FK_Enrollments_Users\``);
        await queryRunner.query(`ALTER TABLE \`enrollments\` DROP FOREIGN KEY \`FK_Enrollments_Courses\``);
        await queryRunner.query(`ALTER TABLE \`topics\` DROP FOREIGN KEY \`FK_Topics_Courses\``);
        await queryRunner.query(`ALTER TABLE \`questions\` DROP FOREIGN KEY \`FK_Questions_Stimulus\``);
        await queryRunner.query(`ALTER TABLE \`questions\` DROP FOREIGN KEY \`FK_Questions_Topics\``);
        await queryRunner.query(`ALTER TABLE \`questions\` DROP FOREIGN KEY \`FK_Questions_Exams\``);
        await queryRunner.query(`ALTER TABLE \`question_solutions\` DROP FOREIGN KEY \`FK_QuestionSolutions_Questions\``);
        await queryRunner.query(`ALTER TABLE \`solution_images\` DROP FOREIGN KEY \`FK_SolutionImages_QuestionSolution\``);
        await queryRunner.query(`ALTER TABLE \`statement_correct_answers\` DROP FOREIGN KEY \`FK_StatementCorrectAnswers_Statements\``);
        await queryRunner.query(`ALTER TABLE \`statement_correct_answers\` DROP FOREIGN KEY \`FK_StatementCorrectAnswers_Questions\``);
        await queryRunner.query(`ALTER TABLE \`fill_in_blank_correct_answers\` DROP FOREIGN KEY \`FK_FillInBlankCorrectAnswers_Questions\``);
        await queryRunner.query(`ALTER TABLE \`mcq_correct_answers\` DROP FOREIGN KEY \`FK_McqCorrectAnswers_Questions\``);
        await queryRunner.query(`ALTER TABLE \`question_choices\` DROP FOREIGN KEY \`FK_QuestionChoices_Questions\``);
        await queryRunner.query(`ALTER TABLE \`question_images\` DROP FOREIGN KEY \`FK_QuestionImages_Questions\``);
        await queryRunner.query(`ALTER TABLE \`stimulus_images\` DROP FOREIGN KEY \`FK_StimulusImages_Stimulus\``);
        await queryRunner.query(`ALTER TABLE \`exams\` DROP FOREIGN KEY \`FK_Exams_Courses\``);
        await queryRunner.query(`ALTER TABLE \`exams\` DROP FOREIGN KEY \`FK_Exams_Users\``);
        await queryRunner.query(`ALTER TABLE \`exam_attempts\` DROP FOREIGN KEY \`FK_Attempts_Users\``);
        await queryRunner.query(`ALTER TABLE \`exam_attempts\` DROP FOREIGN KEY \`FK_Attempts_Exams\``);
        await queryRunner.query(`ALTER TABLE \`attempt_answers\` DROP FOREIGN KEY \`FK_AttemptAnswers_Attempts\``);
        await queryRunner.query(`ALTER TABLE \`attempt_answers\` DROP FOREIGN KEY \`FK_AttemptAnswers_Questions\``);
        await queryRunner.query(`ALTER TABLE \`statement_attempt_answers\` DROP FOREIGN KEY \`FK_StatementAttemptAnswers_QuestionStatements\``);
        await queryRunner.query(`ALTER TABLE \`statement_attempt_answers\` DROP FOREIGN KEY \`FK_StatementAttemptAnswers_AttemptAnswers\``);
        await queryRunner.query(`ALTER TABLE \`question_statements\` DROP FOREIGN KEY \`FK_QuestionStatements_Questions\``);
        await queryRunner.query(`ALTER TABLE \`fill_in_blank_attempt_answers\` DROP FOREIGN KEY \`FK_FibAttemptAnswers_AttemptAnswers\``);
        await queryRunner.query(`ALTER TABLE \`exam_files\` DROP FOREIGN KEY \`FK_ExamFiles_Exams\``);
        await queryRunner.query(`ALTER TABLE \`course_teachers\` DROP FOREIGN KEY \`FK_CourseTeachers_Courses\``);
        await queryRunner.query(`ALTER TABLE \`course_teachers\` DROP FOREIGN KEY \`FK_CourseTeachers_Users\``);
        await queryRunner.query(`ALTER TABLE \`tokens\` DROP FOREIGN KEY \`FK_Tokens_Users\``);
        await queryRunner.query(`DROP INDEX \`REL_29e96a6705c871fd0022e5d2fd\` ON \`mcq_attempt_answer\``);
        await queryRunner.query(`DROP TABLE \`mcq_attempt_answer\``);
        await queryRunner.query(`DROP INDEX \`REL_9e432b7df0d182f8d292902d1a\` ON \`profiles\``);
        await queryRunner.query(`DROP TABLE \`profiles\``);
        await queryRunner.query(`DROP TABLE \`users\``);
        await queryRunner.query(`DROP TABLE \`subjects\``);
        await queryRunner.query(`DROP TABLE \`courses\``);
        await queryRunner.query(`DROP INDEX \`UQ_enrollments_student_id_course_id\` ON \`enrollments\``);
        await queryRunner.query(`DROP TABLE \`enrollments\``);
        await queryRunner.query(`DROP TABLE \`topics\``);
        await queryRunner.query(`DROP TABLE \`questions\``);
        await queryRunner.query(`DROP TABLE \`question_solutions\``);
        await queryRunner.query(`DROP TABLE \`solution_images\``);
        await queryRunner.query(`DROP INDEX \`REL_5d2c47d06fd4fba19652a99396\` ON \`statement_correct_answers\``);
        await queryRunner.query(`DROP INDEX \`UQ_statement_correct_answers_question_id_statement_id\` ON \`statement_correct_answers\``);
        await queryRunner.query(`DROP INDEX \`IDX_5d2c47d06fd4fba19652a99396\` ON \`statement_correct_answers\``);
        await queryRunner.query(`DROP TABLE \`statement_correct_answers\``);
        await queryRunner.query(`DROP TABLE \`fill_in_blank_correct_answers\``);
        await queryRunner.query(`DROP INDEX \`REL_3b28b78de8f028aad9b1318cef\` ON \`mcq_correct_answers\``);
        await queryRunner.query(`DROP INDEX \`IDX_3b28b78de8f028aad9b1318cef\` ON \`mcq_correct_answers\``);
        await queryRunner.query(`DROP TABLE \`mcq_correct_answers\``);
        await queryRunner.query(`DROP TABLE \`question_choices\``);
        await queryRunner.query(`DROP TABLE \`question_images\``);
        await queryRunner.query(`DROP TABLE \`stimulus\``);
        await queryRunner.query(`DROP TABLE \`stimulus_images\``);
        await queryRunner.query(`DROP TABLE \`exams\``);
        await queryRunner.query(`DROP TABLE \`exam_attempts\``);
        await queryRunner.query(`DROP INDEX \`UQ_attempt_answers_question_id_attempt_id\` ON \`attempt_answers\``);
        await queryRunner.query(`DROP TABLE \`attempt_answers\``);
        await queryRunner.query(`DROP INDEX \`UQ_statement_attempt_answers_attempt_answer_id_statement_id\` ON \`statement_attempt_answers\``);
        await queryRunner.query(`DROP TABLE \`statement_attempt_answers\``);
        await queryRunner.query(`DROP TABLE \`question_statements\``);
        await queryRunner.query(`DROP INDEX \`UQ_fill_in_blank_attempt_answers_attempt_answer_id_position\` ON \`fill_in_blank_attempt_answers\``);
        await queryRunner.query(`DROP TABLE \`fill_in_blank_attempt_answers\``);
        await queryRunner.query(`DROP TABLE \`exam_files\``);
        await queryRunner.query(`DROP INDEX \`UQ_course_teachers_teacher_id_course_id\` ON \`course_teachers\``);
        await queryRunner.query(`DROP TABLE \`course_teachers\``);
        await queryRunner.query(`DROP TABLE \`tokens\``);
    }

}
